name: "Setup Python & Dependencies"
description: "Sets up Python, installs UV, and syncs dependencies"
inputs:
    python-version:
        description: "Python version to install"
        required: false
        default: "3.11"

runs:
    using: "composite"
    steps:
        -   name: Checkout Repository
            uses: actions/checkout@v4

        -   name: Install uv
            uses: astral-sh/setup-uv@v5
            with:
                python-version: ${{ inputs.python-version }}

        -   name: Install dependencies
            run: uv sync --all-extras --dev
            shell: bash
