name: Lint Code

on:
    push:

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.10", "3.11", "3.12" ]
        steps:
            -   uses: actions/checkout@v4
            -   name: Run Setup
                uses: ./.github/workflows/setup.yaml
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Run Ruff Linter
                run: uv tool run ruff check
