# .github/workflows/lint.yml
name: Ruff
on:
    push:

jobs:
    lint:
        strategy:
            matrix:
                python-version: [ "3.10", "3.11", "3.12" ]
        uses: ./.github/workflows/setup.yml
        with:
            python-version: ${{ matrix.python-version }}
    
    run-lint:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            -   name: Analysing the code with Ruff
                run: uv tool run ruff check