name: Publish Python Package

on:
    release:
        types: [ published ]

permissions:
    contents: read

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Install uv
                uses: astral-sh/setup-uv@v5
            -   name: Install dependencies
                run: uv sync --all-extras --dev
            -   name: Build package
                run: uv tool run hatch build
            -   name: Publish package
                run: uv tool run hatch publish
