# .github/workflows/test-release.yml
name: Upload Python Package to TestPyPi
on:
    push:
        branches:
            - notnow

permissions:
    contents: read
    id-token: write

jobs:
    setup:
        uses: ./.github/workflows/setup.yml

    test:
        needs: setup
        uses: ./.github/workflows/test.yml

    release:
        needs: test
        runs-on: ubuntu-latest
        steps:
            -   name: Version Package
                run: uv tool run hatch version rc
            -   name: Build package
                run: uv tool run hatch build
            -   name: Publish package
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    repository-url: https://test.pypi.org/legacy/
                    packages-dir: dist/