name: Run Tests

on:
    pull_request:
        branches:
            - notnow

env:
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

jobs:
    test:
        needs: lint  # Ensure linting passes before running tests
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        steps:
            -   name: Run Setup
                uses: ./.github/actions/setup

            -   name: Run Tests
                run: uv tool run hatch test --parallel --all --retries 2
