name: Upload to TestPyPi

on:
    pull_request:
        branches:
            - main

permissions:
    contents: read
    id-token: write

jobs:
    test-release:
        needs: test  # Ensure tests pass before releasing
        runs-on: ubuntu-latest
        steps:
            -   name: Run Setup
                uses: ./.github/actions/setup

            -   name: Version Package
                run: uv tool run hatch version rc

            -   name: Build Package
                run: uv tool run hatch build

            -   name: Publish to TestPyPi
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                    repository-url: https://test.pypi.org/legacy/
                    packages-dir: dist/
